version: "2.0"
services:
  local_nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./conf/conf.d/:/etc/nginx/conf.d/:rw
      - ./conf/nginx.cnf:/etc/nginx/nginx.cnf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    restart: always
    networks:
      - net_fpm72

  local_fpm72:
    image: php:7.2-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./www/:/usr/share/nginx/html/:rw
    restart: always
    networks:
      - net_fpm72
      - net_mysql

  local_mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    restart: always
    networks:
      - net_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "111111"

networks:
  net_fpm72:
  net_mysql:
